<?php

namespace Dywee\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeatureElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeatureElementRepository extends EntityRepository
{
    /*SELECT customValue FROM products
    inner join product_featureelement fe
    on fe.product_id = products.id
    inner join FeatureElement
    on FeatureElement.id = fe.featureelement_id
    WHERE products.id = 1*/

    public function getByProduct($product)
    {
        //return $qb->getQuery()->getResult();
    }
}
