<?php

namespace Dywee\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductStatRepository extends EntityRepository
{

    public function getStats($product, $type = 1, $detail = 'daily')
    {

        $qb = $this->createQueryBuilder('s')
            ->select('sum(s.quantity) as total, s.createdDate, s.type')
            ->where('s.product = :product and s.type = :type')
            ->setParameters(array('product' => $product, 'type' => $type))
            ->orderBy('s.createdDate', 'asc')
            ->setMaxResults(6);

        if($detail == 'daily')
            $qb->groupBy('s.createdDate');

        return $qb->getQuery()->getResult();
    }
}
