<?php

namespace Dywee\ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PackElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackElementRepository extends EntityRepository
{
}
