<?php

namespace Dywee\ProductBundle\Repository;

/**
 * ProductPackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductPackRepository extends BaseProductRepository
{

}
