<?php

namespace Dywee\ProductBundle\Repository;

/**
 * ProductDownloadableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductDownloadableRepository extends BaseProductRepository
{

}
