<?php

namespace Dywee\ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Dywee\ProductBundle\Entity\BaseProduct;
use Dywee\ProductBundle\Entity\ProductStat;

/**
 * ProductStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductStatRepository extends EntityRepository
{

    public function getStats($product, $type, $beginAt, $endAt, $detail = 'day')
    {
        $qb = $this->createQueryBuilder('s')
            ->select('s.createdAt, s.type, YEAR(s.createdAt) as year, MONTH(s.createdAt) as month, DAY(s.createdAt) as day')
            ->andWhere('s.createdAt between :beginAt and :endAt')
            ->setParameters(array(
                    'beginAt' => $beginAt,
                    'endAt' => $endAt)
            )
            ->orderBy('s.createdAt', 'asc');

        $qb->groupBy('s.type, year, month');


        if(is_string($type))
            $qb->where('count(s.id) as total, s.type = :type')
                ->setParameter('type', $type);

        elseif(is_array($type))
        {
            $where = '(';
            $i = 0;
            foreach($type as $typeElement)
            {
                if($i > 0)
                    $where .= ' or ';
                $where .= 's.type = :type'.$i;
                $qb->setParameter('type'.$i++, $typeElement);
            }
            $where .= ')';
            $qb->addSelect('sum(s.quantity) as total');
            $qb->andWhere($where);
        }


        if($detail == 'day')
            $qb->addGroupBy('day');

        return $qb->getQuery()->getResult();
    }

    /**
     * @param BaseProduct $product
     * @param             $event
     * @param             $trackingKey
     *
     * @return array|ProductStat[]
     */
    public function retrievedStatForProduct(BaseProduct $product, $event, $trackingKey)
    {
        $qb = $this->createQueryBuilder('s')
            ->select('s')
            ->where('s.product = :product and s.type = :event and s.trackingKey = :key and s.createdAt between :start and :end')
            ->setParameters(array(
                'product' => $product,
                'event' => $event,
                'key' => $trackingKey,
                'start' => new \DateTime('today'),
                'end' => new \DateTime('tomorrow'),
            ))
        ;

        return $qb->getQuery()->getResult();
    }
}
