<?php

namespace Dywee\ProductBundle\Repository;

/**
 * ProductVariantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductVariantRepository extends \Doctrine\ORM\EntityRepository
{
}
