<?php

namespace Dywee\ProductBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductSubscriptionRepository extends BaseProductRepository
{

}
