<?php

namespace Dywee\ProductBundle\Repository;

/**
 * ProductServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductServiceRepository extends BaseProductRepository
{

}
