<?php

namespace Dywee\ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductStatRepository extends EntityRepository
{

    public function getStats($product, $type, $beginAt, $endAt, $detail = 'day')
    {
        $qb = $this->createQueryBuilder('s')
            ->select('sum(s.quantity) as total, s.createdAt, SUBSTRING(s.createdAt, 0, 10) as dateForGroupBy, s.type')
            ->where('s.product = :product and s.type = :type and s.createdAt between :beginAt and :endAt')
            ->setParameters(array(
                'product' => $product,
                'type' => $type,
                'beginAt' => $beginAt,
                'endAt' => $endAt)
            )
            ->orderBy('s.createdAt', 'asc');

        if($detail == 'day')
            $qb->groupBy('dateForGroupBy');

        return $qb->getQuery()->getResult();
    }
}
