<?php

namespace Dywee\ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductStatRepository extends EntityRepository
{

    public function getStats($product, $type = 1, $detail = 'daily')
    {
        $date = new \DateTime("previous week");
        $qb = $this->createQueryBuilder('s')
            ->select('sum(s.quantity) as total, s.createdDate, s.type')
            ->where('s.product = :product and s.type = :type and s.createdDate > :date')
            ->setParameters(array('product' => $product, 'type' => $type, 'date' => $date))
            ->orderBy('s.createdDate', 'asc');

        if($detail == 'daily')
            $qb->groupBy('s.createdDate');

        return $qb->getQuery()->getResult();
    }
}
