<?php

namespace Dywee\ProductBundle\Controller\Rest;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class ProductRestController extends BaseProductRestController
{
    /**
     * @Route(name="product_table_rest", path="admin/product/rest")
     */
    public function tableAction(Request $request)
    {
        return parent::tableAction($request); // TODO: Change the autogenerated stub
    }
}
